### ISSUE TITLE
PS_RETURN_PREFIX cannot be fixed

### ISSUE THREAD

**Issue by juank2808** [Matt75/fixconfigurationlang#1]
Hi i'm usisng your module because this 
![imagen](https://user-images.githubusercontent.com/14195668/58249300-c9599580-7d5e-11e9-8263-01d0f29ca661.png)

**Comment by Matt75** [comment]
Hi,

Thanks for reporting this issue 👍

I fixed it with version 1.0.4, you can download it here : https://github.com/Matt75/fixconfigurationlang/releases/tag/1.0.4

Please test and feedback 😄

**Comment by juank2808** [comment]
Oh thanks this is solved!
